version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_d  ocker
    environment:
      MYSQL_ROOT_PASSWORD: Shreyash@22
      MYSQL_DATABASE: scmdb
    ports:
      - "3307:3306"

    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Shreyash@22

    ports:
      - "8081:80"
    depends_on:
      - mysql
  springboot:
    build: .
    container_name: scm_springboot_project
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: scmdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Shreyash@22
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USERNAME: shreyash112203@gmail.com
      EMAIL_PASSWORD: frnb ixvy akwq kydd
      EMAIL_DOMAIN: smtp.gmail.com
      CLOUDINARY_API_KEY: 966361831981928
      CLOUDINARY_API_SECRET: j1NfmmnEi8l_Ozbn6EjFTkoA_-U
      CLOUDINARY_NAME: dmkycccsx
    ports:
      - "8082:8080"
    depends_on:
      - mysql
volumes:
  mysql_data:
